web:
  jwt:
    publicKeyFile: classpath:public.key
    privateKeyFile: classpath:private.key
    issuer: shmanchkin
    access-token-expiration: 69420
    refresh-cookie-path: "/api/auth/refresh" # Explicit full path
  allowed-origins:
    - http://localhost:3000
  unauthenticated-path-matchers:
    - "/games"
    - "/games/subscribe"
    - "/auth/signIn"
    - "/swagger-ui.html"        # openapi
    - "/webjars/swagger-ui/**"  # openapi
    - "/v3/api-docs/**"         # openapi

server:
  http2:
    enabled: true

spring:
  webflux:
    base-path: /api